<?php

/** @var $block \Codilar\Afbt\Block\AfbtHandler */
?>

<?php if ($block->isEnabled()): ?>
    <div class="afbt-container">
        <img src="https://upload.wikimedia.org/wikipedia/commons/6/66/Loadingsome.gif" width="100" height="100" />
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "afbtHandler": {
                    "afbtFetchUrl": "<?php echo $block->getFetchUrl() ?>",
                    "product_id": "<?php echo $block->getProduct()->getId() ?>",
                    "addToCartUrl": "<?php echo $block->getCartAddUrl() ?>"
                }
            }
        }
    </script>
    <style>
        .fbt-container{
            margin-bottom: 30px;
            margin-top: 30px;
        }
        .block-container .product-name{
            display: block;
            display: -webkit-box;
            max-width: 100%;
            height: 39.2px;
            margin: 10px auto 5px;
            font-size: 14px;
            line-height: 1.4;
            -webkit-line-clamp: 2;
            -webkit-box-orient: vertical;
            overflow: hidden;
            text-overflow: ellipsis;
        }
        .price-block .item-price{
            margin-top: 1rem;
            font-weight: 600;
        }
        .grant-total{
            margin-top: 20px;
        }
        .grant-total .price{
            font-size: 16px;
            font-weight: 600;
        }
        .fbt-container .owl-item .column-item{
            border-right: 1px solid #ccc;
        }
        .row-fbt:after{
            display: table;
            content: '';
            clear: both;
        }
        .column-2{
            width: 48%;
            float: left;
        }
        .additional-product{
            width: 4%;
            float: left;
            text-align: center;
        }
        .fbt-image-container{
            display: block;
            height: 0;
            overflow: hidden;
            position: relative;
            z-index: 1;
            padding-top: 125%
        }
        .fbt-image-container img{
            bottom: 0;
            display: block;
            height: auto;
            left: 0;
            margin: auto;
            max-width: 100%;
            position: absolute;
            right: 0;
            top: 0;
        }
        .block-container .pad-block{
            padding: 10px;
        }
    </style>
<?php endif; ?>
