<?php

/** @var $block \Codilar\Afbt\Block\AfbtHandler */
?>

<?php if ($block->isEnabled()): ?>
    <div class="afbt-container">
        <div class="loader-block">
            <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
                 alt="<?= /* @escapeNotVerified */ __('Loading...') ?>">
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "afbtHandler": {
                    "afbtFetchUrl": "<?php echo $block->getFetchUrl() ?>",
                    "product_id": "<?php echo $block->getProduct()->getId() ?>",
                    "addToCartUrl": "<?php echo $block->getCartAddUrl() ?>"
                }
            }
        }
    </script>


<?php endif; ?>

<div class="related-block">
    <h2>Related Products</h2>
    <div class="fbt-container">
        <div class="row-fbt related-block-container owl-carousel owl-theme" id="related-carousel-blog">
            <div class="column-item">
                <div class="row-fbt container-flex-container">
                    <div class="row-fbt block-container-flex">
                        <div class="block-container">
                            <div class="pad-block">
                                <div class="fbt-image-container">
                                    <a href="<%= productsData.parent_product.url %>" title="<%= productsData.parent_product.name %>">
                                        <img src="http://127.0.0.1/magento2-fbt/pub/media/catalog/product/cache/207e23213cf636ccdef205098cf3c8a3/m/b/mb02-gray-0.jpg">
                                    </a>
                                </div>
                                <a class="product-name" href="<%= productsData.parent_product.url %>" title="<%= productsData.parent_product.name %>">
                                    Didi Sport Watch
                                </a>
                                <div class="price-block">
                                   USD 1000
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column-item">
                <div class="row-fbt container-flex-container">
                    <div class="row-fbt block-container-flex">
                        <div class="block-container">
                            <div class="pad-block">
                                <div class="fbt-image-container">
                                    <a href="<%= productsData.parent_product.url %>" title="<%= productsData.parent_product.name %>">
                                        <img src="http://127.0.0.1/magento2-fbt/pub/media/catalog/product/cache/207e23213cf636ccdef205098cf3c8a3/m/b/mb02-gray-0.jpg">
                                    </a>
                                </div>
                                <a class="product-name" href="<%= productsData.parent_product.url %>" title="<%= productsData.parent_product.name %>">
                                    Didi Sport Watch
                                </a>
                                <div class="price-block">
                                    USD 1000
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column-item">
                <div class="row-fbt container-flex-container">
                    <div class="row-fbt block-container-flex">
                        <div class="block-container">
                            <div class="pad-block">
                                <div class="fbt-image-container">
                                    <a href="<%= productsData.parent_product.url %>" title="<%= productsData.parent_product.name %>">
                                        <img src="http://127.0.0.1/magento2-fbt/pub/media/catalog/product/cache/207e23213cf636ccdef205098cf3c8a3/m/b/mb02-gray-0.jpg">
                                    </a>
                                </div>
                                <a class="product-name" href="<%= productsData.parent_product.url %>" title="<%= productsData.parent_product.name %>">
                                    Didi Sport Watch
                                </a>
                                <div class="price-block">
                                    USD 1000
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column-item">
                <div class="row-fbt container-flex-container">
                    <div class="row-fbt block-container-flex">
                        <div class="block-container">
                            <div class="pad-block">
                                <div class="fbt-image-container">
                                    <a href="<%= productsData.parent_product.url %>" title="<%= productsData.parent_product.name %>">
                                        <img src="http://127.0.0.1/magento2-fbt/pub/media/catalog/product/cache/207e23213cf636ccdef205098cf3c8a3/m/b/mb02-gray-0.jpg">
                                    </a>
                                </div>
                                <a class="product-name" href="<%= productsData.parent_product.url %>" title="<%= productsData.parent_product.name %>">
                                    Didi Sport Watch
                                </a>
                                <div class="price-block">
                                    USD 1000
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column-item">
                <div class="row-fbt container-flex-container">
                    <div class="row-fbt block-container-flex">
                        <div class="block-container">
                            <div class="pad-block">
                                <div class="fbt-image-container">
                                    <a href="<%= productsData.parent_product.url %>" title="<%= productsData.parent_product.name %>">
                                        <img src="http://127.0.0.1/magento2-fbt/pub/media/catalog/product/cache/207e23213cf636ccdef205098cf3c8a3/m/b/mb02-gray-0.jpg">
                                    </a>
                                </div>
                                <a class="product-name" href="<%= productsData.parent_product.url %>" title="<%= productsData.parent_product.name %>">
                                    Didi Sport Watch
                                </a>
                                <div class="price-block">
                                    USD 1000
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column-item">
                <div class="row-fbt container-flex-container">
                    <div class="row-fbt block-container-flex">
                        <div class="block-container">
                            <div class="pad-block">
                                <div class="fbt-image-container">
                                    <a href="<%= productsData.parent_product.url %>" title="<%= productsData.parent_product.name %>">
                                        <img src="http://127.0.0.1/magento2-fbt/pub/media/catalog/product/cache/207e23213cf636ccdef205098cf3c8a3/m/b/mb02-gray-0.jpg">
                                    </a>
                                </div>
                                <a class="product-name" href="<%= productsData.parent_product.url %>" title="<%= productsData.parent_product.name %>">
                                    Didi Sport Watch
                                </a>
                                <div class="price-block">
                                    USD 1000
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column-item">
                <div class="row-fbt container-flex-container">
                    <div class="row-fbt block-container-flex">
                        <div class="block-container">
                            <div class="pad-block">
                                <div class="fbt-image-container">
                                    <a href="<%= productsData.parent_product.url %>" title="<%= productsData.parent_product.name %>">
                                        <img src="http://127.0.0.1/magento2-fbt/pub/media/catalog/product/cache/207e23213cf636ccdef205098cf3c8a3/m/b/mb02-gray-0.jpg">
                                    </a>
                                </div>
                                <a class="product-name" href="<%= productsData.parent_product.url %>" title="<%= productsData.parent_product.name %>">
                                    Didi Sport Watch
                                </a>
                                <div class="price-block">
                                    USD 1000
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column-item">
                <div class="row-fbt container-flex-container">
                    <div class="row-fbt block-container-flex">
                        <div class="block-container">
                            <div class="pad-block">
                                <div class="fbt-image-container">
                                    <a href="<%= productsData.parent_product.url %>" title="<%= productsData.parent_product.name %>">
                                        <img src="http://127.0.0.1/magento2-fbt/pub/media/catalog/product/cache/207e23213cf636ccdef205098cf3c8a3/m/b/mb02-gray-0.jpg">
                                    </a>
                                </div>
                                <a class="product-name" href="<%= productsData.parent_product.url %>" title="<%= productsData.parent_product.name %>">
                                    Didi Sport Watch
                                </a>
                                <div class="price-block">
                                    USD 1000
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column-item">
                <div class="row-fbt container-flex-container">
                    <div class="row-fbt block-container-flex">
                        <div class="block-container">
                            <div class="pad-block">
                                <div class="fbt-image-container">
                                    <a href="<%= productsData.parent_product.url %>" title="<%= productsData.parent_product.name %>">
                                        <img src="http://127.0.0.1/magento2-fbt/pub/media/catalog/product/cache/207e23213cf636ccdef205098cf3c8a3/m/b/mb02-gray-0.jpg">
                                    </a>
                                </div>
                                <a class="product-name" href="<%= productsData.parent_product.url %>" title="<%= productsData.parent_product.name %>">
                                    Didi Sport Watch
                                </a>
                                <div class="price-block">
                                    USD 1000
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column-item">
                <div class="row-fbt container-flex-container">
                    <div class="row-fbt block-container-flex">
                        <div class="block-container">
                            <div class="pad-block">
                                <div class="fbt-image-container">
                                    <a href="<%= productsData.parent_product.url %>" title="<%= productsData.parent_product.name %>">
                                        <img src="http://127.0.0.1/magento2-fbt/pub/media/catalog/product/cache/207e23213cf636ccdef205098cf3c8a3/m/b/mb02-gray-0.jpg">
                                    </a>
                                </div>
                                <a class="product-name" href="<%= productsData.parent_product.url %>" title="<%= productsData.parent_product.name %>">
                                    Didi Sport Watch
                                </a>
                                <div class="price-block">
                                    USD 1000
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column-item">
                <div class="row-fbt container-flex-container">
                    <div class="row-fbt block-container-flex">
                        <div class="block-container">
                            <div class="pad-block">
                                <div class="fbt-image-container">
                                    <a href="<%= productsData.parent_product.url %>" title="<%= productsData.parent_product.name %>">
                                        <img src="http://127.0.0.1/magento2-fbt/pub/media/catalog/product/cache/207e23213cf636ccdef205098cf3c8a3/m/b/mb02-gray-0.jpg">
                                    </a>
                                </div>
                                <a class="product-name" href="<%= productsData.parent_product.url %>" title="<%= productsData.parent_product.name %>">
                                    Didi Sport Watch
                                </a>
                                <div class="price-block">
                                    USD 1000
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .related-block-container .block-container{
        width: 100%;
    }
</style>
<script>
    require(['jquery', 'owlCarousel'], function($, owlCarousel) {
        var owl = $("#related-carousel-blog");
        owl.owlCarousel({
            loop: false,
            nav: true,
            margin: 15,
            navText: ['<div class="left-arrow">', '<div class="right-arrow">'],
            responsive: {
                0: {
                    items: 2,
                    margin: 0
                },
                600: {
                    items: 2,
                    margin: 0
                },
                1000: {
                    items: 5
                }
            }
        });
        checkClasses();
        owl.on('translated.owl.carousel', function (event) {
            checkClasses();
        });

        function checkClasses() {
            var total = $('.fbt-container .owl-stage .owl-item.active').length;

            $('.fbt-container .owl-stage .owl-item').removeClass('lastActiveItem');

            $('.fbt-container .owl-stage .owl-item.active').each(function (index) {
                if (index === total - 1 && total > 1) {
                    // this is the last one
                    $(this).addClass('lastActiveItem');
                }
            });
        }
    });
</script>