<?php

/** @var $block \Codilar\Afbt\Block\AfbtHandler */
?>

<?php if ($block->isEnabled()): ?>
    <div class="afbt-container">
        <img src="https://upload.wikimedia.org/wikipedia/commons/6/66/Loadingsome.gif" width="100" height="100" />
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "afbtHandler": {
                    "afbtFetchUrl": "<?php echo $block->getFetchUrl() ?>",
                    "product_id": "<?php echo $block->getProduct()->getId() ?>",
                    "addToCartUrl": "<?php echo $block->getCartAddUrl() ?>",
                    "form_key": "<?php echo $block->getFormKey() ?>"
                }
            }
        }
    </script>


<?php endif; ?>